languageCode = "en-us"
title = "Fanny Jiang"
baseurl = "https://fanny-jiang.com"
theme = "prologue"
publishDir = "public"

[params]
  name = "Fanny Jiang"
  description = "Software Engineer"
  copyright = "MIT"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://www.twitter.com/heygirlcode"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://www.github.com/fanny-jiang"

[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://www.medium.com/@heygirlcode"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:hello@fanny-jiang.com"

# Portfolio column one

[[params.portfolio1]]
  title = "Codeboard"
  alt = "Codeboard"
  source = "img/codeboard-screenshot.png"
  url = "https://code-board.herokuapp.com/"

# Portfolio column two

[[params.portfolio2]]
  title = "What's Happening? Facebook Messenger Chat Bot"
  alt = "What's Happening? Facebook Messenger Chat Bot"
  source = "img/robot_1024.jpg"
  url = "https://m.me/whatshappeningEVE"

# Portfolio column 3

[[params.portfolio3]]
  title = "Tech Talk: How to Write Asynchronous JS with ES6 Generators"
  alt = "Tech Talk: How to Write Asynchronous JS with ES6 Generators"
  source = "img/generators-screenshot.png"
  url = "https://www.youtube.com/watch?v=-YH29Bs-Zls"

# Resume

[[params.projects]]
  title = "Codeboard"
  summary = "A web application that uses audio and in-browser code testing to help users prepare for a technical interview"
  accomplishments = "Implemented bottom nav bar functionality, front end design and styling"
  technologies = "Built with React/Redux, Node, Express, PostgreSQL, Web Speech API, Bootstrap, and Material UI using the Agile development method"
  url = "https://code-board.herokuapp.com/"
  github = "https://github.com/fanny-jiang/codeboard"


