languageCode = "en-us"
title = "Fanny Jiang"
baseurl = "http://www.fanny-jiang.com/"
theme = "prologue"

[params]
  name = "Fanny Jiang"
  description = "Software Engineer"
  copyright = "MIT"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://www.twitter.com/heygirlcode"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://www.github.com/fanny-jiang"

[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://www.medium.com/@heygirlcode"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:hello@fanny-jiang.com"

# Portfolio column one

[[params.portfolio1]]
  title = "What's Happening? Facebook Messenger Chat Bot"
  alt = "What's Happening? Facebook Messenger Chat Bot"
  source = "img/pic02.jpg"
  url = "https://m.me/whatshappeningEVE"

# Portfolio column two

[[params.portfolio2]]
  title = "Codeboard"
  alt = "Codeboard"
  source = "img/pic03.jpg"
  url = "https://www.code-board.tech"

# Portfolio column 3

[[params.portfolio3]]
  title = "Tech Talk: How to Write Asynchronous JS with ES6 Generators"
  alt = "Tech Talk: How to Write Asynchronous JS with ES6 Generators"
  source = "img/pic04.jpg"
  url = "https://www.youtube.com/watch?v=-YH29Bs-Zls"

