languageCode = "en-us"
title = "Fanny Jiang"
baseurl = "https://fanny-jiang.com"
theme = "prologue"
publishDir = "public"

[params]
  name = "Fanny Jiang"
  description = "Software Engineer"
  copyright = "MIT"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://www.twitter.com/heygirlcode"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://www.github.com/fanny-jiang"

[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://www.medium.com/@heygirlcode"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:hello@fanny-jiang.com"

# Portfolio column one

[[params.portfolio1]]
  title = "Codeboard"
  alt = "Codeboard"
  source = "img/codeboard-screenshot.png"
  url = "https://code-board.herokuapp.com/"

# Portfolio column two

[[params.portfolio2]]
  title = "What's Happening? Facebook Messenger Chat Bot"
  alt = "What's Happening? Facebook Messenger Chat Bot"
  source = "img/robot_1024.jpg"
  url = "https://m.me/whatshappeningEVE"

# Portfolio column 3

[[params.portfolio3]]
  title = "Tech Talk: How to Write Asynchronous JS with ES6 Generators"
  alt = "Tech Talk: How to Write Asynchronous JS with ES6 Generators"
  source = "img/generators-screenshot.png"
  url = "https://www.youtube.com/watch?v=-YH29Bs-Zls"

# Resume

[[params.projects]]
  title = "Codeboard"
  summary = "A web application that uses audio and in-browser code testing to help users prepare for a technical interview"
  accomplishments = "Implemented bottom nav bar functionality, front end design and styling"
  technologies = "Built with React/Redux, Node, Express, PostgreSQL, Web Speech API, Bootstrap, and Material UI using the Agile development method"
  url = "https://code-board.herokuapp.com/"
  github = "https://github.com/fanny-jiang/codeboard"

[[params.projects]]
  title = "What's Happening?"
  summary = "A Facebook Messenger chat bot that uses natural language processing to suggest nearby events"
  accomplishments = "Implemented webhooks between the 3rd party APIs and server for real-time data retrieval"
  technologies = "Built with Node, Express, API.AI, Eventbrite API, Facebook Messenger Platform"
  url = "https://m.me/whatshappeningEVE"
  github = "https://github.com/fanny-jiang/whats-happening-bot"

[[params.techtalk]]
  title = "How to Write Asynchronous JS with ES6 Generators"
  summary = "Ten-minute talk delivered at Fullstack Academy introducing ES6 Generators and how they can be used in conjunction with JavaScript Promises to write cleaner and easier to read asynchronous JavaScript"
  url = "https://youtube.com/watch?v=-YH29Bs-Zls"

[[params.datadog]]
  title = "Solutions Engineer"
  employer = "Datadog, New York, NY, Jan 2018 - Present"

[[params.datadog.experience]]
  listitem = "Respond to customer requests, quickly, accurately"

[[params.datadog.experience]]
  listitem = "Reproduce issues and file bugs"

[[params.datadog.experience]]
  listitem = "Build out documentation, including writing API examples"

[[params.ad60]]
  title = "Full Stack Software Engineer, Contract"
  employer = "AD:60, New York, NY, Oct 2017 - Dec 2017"

[[params.ad60.experience]]
  listitem = "Design and implement back-end database models and routes using PostgreSQL and Node/Hapi for mobile app"

[[params.ad60.experience]]
  listitem = "Create and build routes and database architecture to securely store encrypted data and authenticate users"

[[params.ad60.experience]]
  listitem = "Develop maintainable utilities to securely handle user authentication, financial transactions, and business logic "

[[params.ad60.experience]]
  listitem = "Create and develop front-end administrator panel web app using Angular4 and ngrx store for state management"

[[params.fellowship]]
  title = "Teaching Fellow"
  employer = "Fullstack Academy of Code, New York, NY, June 2017 - Sept 2017"

[[params.fellowship.experience]]
  listitem = "Teach and mentor 20 students, supporting their wellbeing and academic success in the immersive program"

[[params.fellowship.experience]]
  listitem = "Assist instructors during programming workshops, answering students’ questions and guiding their learning process"

[[params.fellowship.experience]]
  listitem = "Lead lectures on data structures and algorithms, optimization, functional programming, and number theory"

[[params.fellowship.experience]]
  listitem = "Manage 2 student projects as product manager and technical mentor, leading code reviews and daily advising"

[[params.fellowship.experience]]
  listitem = "Evaluate exams and provide constructive technical feedback"

[[params.fellowship.experience]]
  listitem = "Conduct admissions interviews 2x weekly delivering technical challenges in JavaScript and Ruby and assessing each applicant’s academic ability and fit within the Fullstack Academy community"

[[params.oscar]]
  title = "Member Services Case Manager"
  employer = "Oscar Health Insurance, New York, NY, Sept 2016 - Feb 2017"

[[params.oscar.experience]]
  listitem = "Interacted with 10 - 20 members daily to resolve complex health insurance issues, resolving 10 - 15 cases weekly"

[[params.oscar.experience]]
  listitem = "Promoted from Member Services Representative in November 2016"

[[params.education.gh]]
  title = "Grace Hopper Program at Fullstack Academy of Code"
  date = "Feb 2017 - May 2017"
  description = "700+ hours of full stack JavaScript coursework at highly selective (8% acceptance rate) immersive software development program for women in New York City"
  url = "http://www.gracehopper.com/"

[[params.education.bu]]
  title = "Boston University"
  grad = "M.S. in Medical Science at the School of Medicine, "
  graddate = "May 2015"
  undergrad = "B.A. in Biology at the College of Arts and Sciences, "
  undergraddate = "May 2013"